from sqlalchemy import Column, String, Float, Integer, DateTime, Text, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from ..database import Base


class WHTransaction(Base):
    """Modelo para Guías de Remisión - Cabecera"""
    __tablename__ = "WH_Transaction"
    
    Transaction = Column(String(50), primary_key=True, index=True)
    Company = Column(String(50))
    WareHouse = Column(String(50))
    Application = Column(String(50))
    TransactionType = Column(String(50))
    DocumentType = Column(String(50))
    DocumentSerie = Column(String(10))
    DocumentNo = Column(String(20))
    TransactionDate = Column(DateTime)
    TransactionCurrency = Column(String(10))
    ServiceType = Column(String(50))
    Period = Column(String(10))
    ExchangeRate = Column(Float)
    DocRef = Column(String(50))
    DocRef1 = Column(String(50))
    FechaFactura = Column(DateTime)
    FechaTraslado = Column(DateTime)
    Employee = Column(String(50))
    Situation = Column(Integer)
    Production = Column(String(50))
    SaleDoc = Column(String(50))
    SaleDocType = Column(String(50))
    SaleDocAbbrev = Column(String(10))
    SaleDocSerie = Column(String(10))
    SaleDocNo = Column(String(20))
    Driver = Column(String(100))
    LicenciaConducir = Column(String(20))
    NroInscripcion = Column(String(20))
    VehicleID = Column(String(20))
    Marca = Column(String(50))
    Transportista = Column(String(100))
    RucTransportista = Column(String(20))
    AddressTransportista = Column(String(200))
    MotivoTraslado = Column(String(100))
    WareHouseTarget = Column(String(50))
    TargetType = Column(String(10))
    TargetAddress = Column(String(200))
    TargetPerson = Column(String(50))
    TargetPersonRUC = Column(String(20))
    TargetPersonName = Column(String(200))
    Total = Column(Float)
    TotalLo = Column(Float)
    TotalEx = Column(Float)
    Comments = Column(Text)
    Voucher = Column(String(50))
    VoucherNo = Column(String(20))
    VoucherDate = Column(DateTime)
    VoucherStatus = Column(String(10))
    VoucherVoid = Column(String(50))
    VoucherVoidNo = Column(String(20))
    VoucherVoidDate = Column(DateTime)
    RejectionDate = Column(DateTime)
    RejectionUser = Column(String(50))
    RejectionReason = Column(Text)
    ApproveUser = Column(String(50))
    ApproveDate = Column(DateTime)
    Status = Column(String(10))
    XLastUser = Column(String(50))
    XLastDate = Column(DateTime)
    ReplicationUnit = Column(String(50))
    FlagFacturado = Column(String(10))
    RegisterUser = Column(String(50))
    TransactionDateSystem = Column(DateTime)
    TransactionUser = Column(String(50))
    TransactionReason = Column(Text)
    FlagDelivery = Column(String(10))
    DocumentCC = Column(String(50))
    ApDocument = Column(String(50))
    flagexittype = Column(String(10))
    flagcustomertype = Column(String(10))
    transactionref = Column(String(50))
    numberop = Column(String(20))
    numberoc = Column(String(20))
    DocRefOrders = Column(String(50))
    SubWareHouse = Column(String(50))
    SubWareHouseTarget = Column(String(50))
    NroOrder = Column(String(20))
    useconfir = Column(String(10))
    Transport = Column(String(50))
    Vehicle = Column(String(50))
    DriverId = Column(String(50))
    id_guia_remision = Column(String(50))
    PesoBruto = Column(Float)
    motivo = Column(Text)
    iselectro = Column(String(10))
    origenaddress = Column(String(200))
    project = Column(String(50))
    etapa = Column(String(50))
    ubigeo_des = Column(String(10))
    envio_nube = Column(String(50))
    phone = Column(String(20))
    correlativo = Column(Integer)
    necesita_aprobacion = Column(Boolean, default=False)
    aprobacion_usuario = Column(String(50))
    
    # Relación con detalles
    detalles = relationship("WHTransactionDetail", back_populates="transaccion")


class WHTransactionDetail(Base):
    """Modelo para Guías de Remisión - Detalle"""
    __tablename__ = "WH_TransactionDetail"
    
    Line = Column(Integer, primary_key=True)
    Transaction = Column(String(50), ForeignKey("WH_Transaction.Transaction"), primary_key=True)
    Unit = Column(String(10))
    QuantityBultos = Column(Float)
    UnitBultos = Column(String(10))
    Item = Column(String(50))
    FlagItemClass = Column(String(10))
    Condition = Column(String(10))
    Lot = Column(String(50))
    LotDueDate = Column(DateTime)
    LotLivestock = Column(String(50))
    Location = Column(String(50))
    Project = Column(String(50))
    ProjectCode = Column(String(50))
    CostCenter = Column(String(50))
    CostCenterCode = Column(String(50))
    ARF1 = Column(String(50))
    ARF1Code = Column(String(50))
    ARF1Value = Column(Float)
    ARF2 = Column(String(50))
    ARF2Code = Column(String(50))
    ARF2Value = Column(Float)
    ARF3 = Column(String(50))
    ARF3Code = Column(String(50))
    ARF3Value = Column(Float)
    PriceLo = Column(Float)
    PriceEx = Column(Float)
    Quantity = Column(Float)
    TotalLo = Column(Float)
    TotalEx = Column(Float)
    TotalTax = Column(Float)
    TotalTaxLo = Column(Float)
    TotalTaxEx = Column(Float)
    ItemCode = Column(String(50))
    ItemDescription = Column(String(200))
    Price = Column(Float)
    Total = Column(Float)
    XLastUser = Column(String(50))
    XLastDate = Column(DateTime)
    ReplicationUnit = Column(String(50))
    Company = Column(String(50))
    Comments = Column(Text)
    Comments01 = Column(Text)
    quantitydispatch = Column(Float)
    quantitydoc = Column(Float)
    unitdoc = Column(String(10))
    unitfactor = Column(Float)
    pricedoc = Column(Float)
    totaldoc = Column(Float)
    EmployeeLocation = Column(String(50))
    Age = Column(Integer)
    ChargeDate = Column(DateTime)
    ChargeHour = Column(Float)
    FlagDateControl = Column(String(10))
    Warehouse = Column(String(50))
    CodCosto = Column(String(50))
    OrderRequisition = Column(String(50))
    kardex2 = Column(String(50))
    motivo = Column(Text)
    codlote = Column(String(50))
    pesada = Column(Float)
    
    # Relación con cabecera
    transaccion = relationship("WHTransaction", back_populates="detalles")
